// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLEloCMsY2PPMvR3G0ncIvjKufdR9Z1o',
    appId: '1:277962436586:web:1f3e9e263808f1fb800c93',
    messagingSenderId: '277962436586',
    projectId: 'dhilwise-machine-test',
    authDomain: 'dhilwise-machine-test.firebaseapp.com',
    storageBucket: 'dhilwise-machine-test.appspot.com',
    measurementId: 'G-7G1RCS9L1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUGuQLQjEE_-iJWnlh5hjgAoPF1ApKp8',
    appId: '1:277962436586:android:623e4704c2a1e4c5800c93',
    messagingSenderId: '277962436586',
    projectId: 'dhilwise-machine-test',
    storageBucket: 'dhilwise-machine-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWlIgTRLP6wTUrp4fvfFfS2SY0IWtm24Q',
    appId: '1:277962436586:ios:334b81c0267581af800c93',
    messagingSenderId: '277962436586',
    projectId: 'dhilwise-machine-test',
    storageBucket: 'dhilwise-machine-test.appspot.com',
    iosBundleId: 'com.example.dhilwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWlIgTRLP6wTUrp4fvfFfS2SY0IWtm24Q',
    appId: '1:277962436586:ios:3ee59b8c9158116a800c93',
    messagingSenderId: '277962436586',
    projectId: 'dhilwise-machine-test',
    storageBucket: 'dhilwise-machine-test.appspot.com',
    iosBundleId: 'com.example.dhilwise.RunnerTests',
  );
}
